import './globals.css'
import type { Metadata } from 'next'
import { Raleway, Open_Sans } from 'next/font/google'

const raleway = Raleway({ subsets: ['latin'], display: 'swap', variable: '--font-raleway' })
const open_sans = Open_Sans({ subsets: ['latin'], display: 'swap', variable: '--font-open-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${raleway.variable} ${open_sans.variable}`}>
      <body>{children}</body>
    </html>
  )
}
